# Connect to Ansible on the localhost
- hosts: localhost
  gather_facts: false
  connection: local
  user: remote

  # Dynamic variables. Prompt the user to fill in. Use default if nothing provided by user
  vars_prompt:

    # What vCenter should the VM be deployed to.
    - name: "vcenter_hostname"
      prompt: "Please enter the vCenter host"
      private: no
      default: vcenter.kuisc.com

    # Username to log in to vCenter with.
    - name: "vcenter_username"
      private: no
      default: 'it416test'
      prompt: "Please enter your username"

    # Password to log in to vCenter with.
    - name: "vcenter_password"
      default: 'IT416Test!'
      prompt: "Please enter your password"

      # Resource pool to create the VM in.
    - name: "resource_pool"
      prompt: "What resource pool would you like to create the VM in?"
      private: no
      default: "IT 416 - System Integration and Architecture"

    # Any notes you would like put in the VM information.
    - name: "notes"
      prompt: "Please enter any notes"
      private: no
      default: "Deployed with Ansible"


- name: Kali Ansible VM
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    resource_pool: '{{ resource_pool }}'
    validate_certs: no
    datacenter: Edwards
    state: present
    folder: /Edwards/BEST/IT 416 - System Integration and Architecture/Ladage
    template: Kali-Template
    name: IT416-Kali-Ladage
    hardware:
      memory_mb: 512
      num_cpus: 4
    cluster: BEST
    networks:
      - name: VM Network
        ip: 192.168.5.244
        netmask: 255.255.255.0
        gateway: 192.168.5.254
    wait_for_ip_address: True
    customization:
      domain: internal.it416.com
      dns_servers:
        - 8.8.8.8
  delegate_to: localhost